// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "buyfakett",
            "url": "https://github.com/buyfakett"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/health/sync": {
            "post": {
                "description": "App选定时间段后，将该时间段内的健康数据上传到服务端",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "健康数据"
                ],
                "summary": "App上传指定时间段的健康数据",
                "parameters": [
                    {
                        "description": "上传数据",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/health.SyncHealthDataReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/health.SyncHealthDataResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/health.SyncHealthDataResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/health.SyncHealthDataResp"
                        }
                    }
                }
            }
        },
        "/api/health/upload": {
            "post": {
                "description": "上传Apple健康导出的zip文件",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "健康数据"
                ],
                "summary": "上传健康数据",
                "parameters": [
                    {
                        "type": "file",
                        "description": "zip文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/health.ImportDataResp"
                        }
                    }
                }
            }
        },
        "/api/metrics": {
            "get": {
                "tags": [
                    "监控"
                ],
                "summary": "普罗米修斯监控",
                "responses": {}
            }
        },
        "/api/ping": {
            "get": {
                "description": "测试网络接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "测试"
                ],
                "summary": "测试网络接口",
                "responses": {}
            }
        },
        "/api/server_info": {
            "get": {
                "description": "服务信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "测试"
                ],
                "summary": "服务信息",
                "responses": {}
            }
        },
        "/api/user/test_token": {
            "get": {
                "description": "测试token权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "测试token权限",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.CommonResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "health.ImportDataResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/model.ImportLog"
                },
                "message": {
                    "type": "string",
                    "example": "导入成功"
                }
            }
        },
        "health.SyncHealthDataReq": {
            "type": "object",
            "required": [
                "end_date",
                "start_date"
            ],
            "properties": {
                "activity_summaries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ActivitySummary"
                    }
                },
                "end_date": {
                    "type": "string"
                },
                "health_records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.HealthRecord"
                    }
                },
                "sleep_analyses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SleepAnalysis"
                    }
                },
                "start_date": {
                    "type": "string"
                },
                "workout_locations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.WorkoutLocation"
                    }
                },
                "workout_routes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.WorkoutRoute"
                    }
                },
                "workouts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Workout"
                    }
                }
            }
        },
        "health.SyncHealthDataResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/health.SyncHealthDataSummary"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "health.SyncHealthDataSummary": {
            "type": "object",
            "properties": {
                "activity_summary_count": {
                    "type": "integer"
                },
                "health_record_count": {
                    "type": "integer"
                },
                "sleep_analysis_count": {
                    "type": "integer"
                },
                "workout_count": {
                    "type": "integer"
                },
                "workout_location_count": {
                    "type": "integer"
                },
                "workout_route_count": {
                    "type": "integer"
                }
            }
        },
        "model.ActivitySummary": {
            "type": "object",
            "properties": {
                "active_energy_burned": {
                    "type": "number"
                },
                "active_energy_burned_goal": {
                    "type": "number"
                },
                "active_energy_burned_unit": {
                    "type": "string"
                },
                "apple_exercise_time": {
                    "type": "number"
                },
                "apple_exercise_time_goal": {
                    "type": "number"
                },
                "apple_exercise_time_unit": {
                    "type": "string"
                },
                "apple_stand_time": {
                    "type": "number"
                },
                "apple_stand_time_goal": {
                    "type": "number"
                },
                "apple_stand_time_unit": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "date_components": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.HealthRecord": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "creation_date": {
                    "type": "string"
                },
                "device": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "hk_quantity_type": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "metadata": {
                    "type": "string"
                },
                "source_name": {
                    "type": "string"
                },
                "source_version": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "model.ImportLog": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "file_name": {
                    "type": "string"
                },
                "file_size": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "record_count": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "model.SleepAnalysis": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "creation_date": {
                    "type": "string"
                },
                "device": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "source_name": {
                    "type": "string"
                },
                "source_version": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "model.Workout": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "creation_date": {
                    "type": "string"
                },
                "device": {
                    "type": "string"
                },
                "duration": {
                    "type": "number"
                },
                "duration_unit": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "metadata": {
                    "type": "string"
                },
                "source_name": {
                    "type": "string"
                },
                "source_version": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "total_distance": {
                    "type": "number"
                },
                "total_distance_unit": {
                    "type": "string"
                },
                "total_energy_burned": {
                    "type": "number"
                },
                "total_energy_burned_unit": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "workout_activity_type": {
                    "type": "string"
                }
            }
        },
        "model.WorkoutLocation": {
            "type": "object",
            "properties": {
                "altitude": {
                    "type": "number"
                },
                "course": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "horizontal_accuracy": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "route_id": {
                    "type": "integer"
                },
                "speed": {
                    "type": "number"
                },
                "timestamp": {
                    "type": "string"
                },
                "vertical_accuracy": {
                    "type": "number"
                }
            }
        },
        "model.WorkoutRoute": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "source_name": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "workout_id": {
                    "type": "integer"
                }
            }
        },
        "response.Code": {
            "type": "integer",
            "enum": [
                200,
                401,
                500,
                504
            ],
            "x-enum-varnames": [
                "Code_Success",
                "Code_Unauthorized",
                "Code_Err",
                "Code_CaptchaErr"
            ]
        },
        "response.CommonResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/response.Code"
                },
                "msg": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
